services:
  - type: web
    name: calculadora-imc
    env: python
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn projeto_imc.projeto_imc.wsgi
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: projeto_imc.settings
      - key: SECRET_KEY
        value: django-insecure--g1(ra$zeny^4j01bx&et*q3510qeq*$@%wmqrt2!45n4*%c#2
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: calculadora.onrender.com,localhost,127.0.0.1
